import "./globals.css";
import { Inter } from "next/font/google";
import { AuthContext } from "./AuthContext";
import { ThemeProvider } from "@/components/themes-provider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} h-screen md:h-full`}>
        {/* <QueryClientProvider client={queryClient}> */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthContext>{children}</AuthContext>
        </ThemeProvider>
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
